#!/usr/bin/env bash
cliphist list | tail -n +101 | cliphist delete
cliphist list | rofi -config ~/dotfiles/rofi/launcher.rasi -theme ~/dotfiles/assets/themes/rofi_clipboard.rasi  -dmenu | cliphist decode | wl-copy
