#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Github : @adi1090x
#
## Rofi   : Power Menu

# Current Theme
dir="$HOME/dotfiles/assets/themes/"
theme='rofi_powermenu'
config="~/dotfiles/rofi/launcher.rasi"

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostname`

# Options
shutdown='   Power off'
reboot='   Reboot'
lock='   Lock'
suspend=' 󰤄  Sleep'
logout=' 󰈆  Exit'
yes=''
no=''

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-config ${config}\
		-p "Uptime: $uptime" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}

# Confirmation CMD
confirm_cmd() {
	niri msg action do-screen-transition --delay-ms 80
	rofi -config ${config}\
	     -theme-str 'window {
		     width: 290px;
		     x-offset: 1610px;
		     }' \
	     -theme-str 'mainbox {
		     children: [ "message", "listview" ];
		     }' \
	     -theme-str 'listview {
		     columns: 2;
		     lines: 1;
		     }' \
	     -theme-str 'element-text {
		     horizontal-align: 0.5;
		     font:"Nothing Font (5x7) 16";
		     }' \
	     -theme-str 'textbox {
		     horizontal-align: 0.5;
		     font:"Nothing Font (5x7) 22";
		     }' \
	     -dmenu \
	     -p 'Confirmation' \
	     -mesg 'Are you Sure?' \
	     -theme ${dir}/${theme}.rasi
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			systemctl reboot
		elif [[ $1 == '--suspend' ]]; then
			systemctl suspend
		elif [[ $1 == '--logout' ]]; then
			niri msg quit
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
		swaylock
        ;;
    $suspend)
		run_cmd --suspend
        ;;
    $logout)
		run_cmd --logout
        ;;
esac
