# GENERAL SETTINGS --------------------------------
# SOURCES
source=~/dotfiles/configs/.config/mango/split_configs/input.conf
source=~/dotfiles/configs/.config/mango/split_configs/rules.conf
source=~/dotfiles/configs/.config/mango/split_configs/scratchpads.conf
source=~/dotfiles/configs/.config/mango/split_configs/layouts.conf
source=~/dotfiles/configs/.config/mango/split_configs/theme.conf
source=~/dotfiles/configs/.config/mango/split_configs/keybinds.conf
# --------------------------------

# EXECUTE @ STARTUP --------
exec-once=~/dotfiles/assets/scripts/startup
exec-once=geany
exec-once=vivaldi
# --------------------------------

# EXECUTE @ CONFIG RELOAD --------
#exec=foo
# --------------------------------

# SYSTEM --------
xwayland_persistence=1
xwayland_ignore_scale=0
syncobj_enable=1
allow_lock_transparent=1
allow_shortcuts_inhibit=1
# --------------------------------

# BEHAVIOUR --------
# focus
focus_on_activate=1
sloppyfocus=1
# cursor
warpcursor=1
cursor_hide_timeout=0
cursor_hide_on_keypress=0
# dragging
drag_warp_cursor=1
drag_tile_to_tile=1
drag_tile_small=1
drag_corner=3
drag_tile_refresh_interval=8.0
drag_floating_refresh_interval=8.0
# monitors
focus_cross_monitor=1
exchange_cross_monitor=1
# tags
focus_cross_tag=0
view_current_to_back=1
tag_carousel=0
tag_num=3
tag_gather=0
# snap
enable_floating_snap=0
snap_distance=30
# borders
no_border_when_single=0
# idle inhibitor
idleinhibit_ignore_visible=0
# --------------------------------
