# CLIENTS --------
# no transparency rule
windowrule=noblur:0,focused_opacity:1,unfocused_opacity:0,appid:^(vivaldi-stable|brave-browser|freetube)

# terminal swallowing
windowrule=isterm:1,appid:^(com.mitchellh.ghostty)$
# --------------------------------

# TAGS --------
tagrule=id:0,layout_name:dwindle
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
# --------------------------------

# MONITORS --------
#PC0
monitorrule=make:Dell Inc.,x:0,y:180
monitorrule=make:JRY,x:1440,y:0
monitorrule=make:UGD,x:1440,y:1080

#LT0
monitorrule=make:BOE,x:0,y:1080
monitorrule=make:Technical Concepts Ltd,width:1920,height:1080,refresh:60,x:0,y:0
# --------------------------------

# LAYERS --------
#layerrule=noblur:1,layer_name:nino
# --------------------------------
